#we tell travis we need super user level permissions.
sudo: required
# we tell Travis we need the Docker CLI preinstalled. it'll get a copy of docker
services:
  - docker

#set of commands to be executed before our test are run.
before_install:
  - docker build -t kob-h/docker-react -f Dockerfile.dev . #use current directory

#will contain commands that has to be executed to actually run our test suite.
#Travis will watch the output of each command, and if in any command Travis will get an exit code
#other than 0 - our build will fail.
script:
  - docker run -e CI=true kob-h/docker-react npm run test

  #according to the data we have on AWS.
deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "docker-react-env"
    bucket_name: "elasticbeanstalk-us-west-2-306476627547"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY #keys provided by amazon that will be typed in Travis CI env variables.
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
